"""Add slug and post_image to posts

Revision ID: faabaa848dff
Revises: 9afdc7614542
Create Date: 2025-05-18 15:24:44.065903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faabaa848dff'
down_revision = '9afdc7614542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('post_image', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('post_image')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
